--------------------------------------------------------
--  DDL for View VWAP_GATEWAY_SERVICE_ZTE_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW VWAP_GATEWAY_SERVICE_ZTE_HOUR (FECHA, WAP_BROWSER_REQUEST_NUMBER, WAP_BROWSER_REQ_SUCCESS_RATIO, HTTP_BROWSER_REQUEST_NUMBER, HTTP_BROWSER_REQ_SUCCESS_RATIO, JAVA_DNLD_REQ_SUCCESS_RATIO, JAVA_DOWNLOAD_REQUEST_NUMBER, MMS_POST_REQUEST_NUMBER, MMS_POST_REQUEST_SUCCESS_RATIO, MMS_GET_REQUEST_NUMBER, MMS_GET_REQUEST_RATIO, PUSH_REQUEST_NUMBER, PUSH_REQUEST_SUCCESS_RATIO, RADIUS_REQUEST_NUMBER, RADIUS_REQUEST_SUCCESS_RATIO, REQUEST_NUMBER, REQUEST_SUCCESS_RATIO, ONLINE_USER_NUMBER, GATEWAY_FORWARD_REQUEST_DELAY, GATEWAY_FORWARD_RESPONSE_DELAY, SP_DELAY, SERVICE_DELAY) AS 
  SELECT  FECHA                               ,
        WAP_BROWSER_REQUEST_NUMBER          ,
        WAP_BROWSER_REQ_SUCCESS_RATIO       ,
        HTTP_BROWSER_REQUEST_NUMBER         ,
        HTTP_BROWSER_REQ_SUCCESS_RATIO      ,
        JAVA_DNLD_REQ_SUCCESS_RATIO         ,
        JAVA_DOWNLOAD_REQUEST_NUMBER        ,
        MMS_POST_REQUEST_NUMBER             ,
        MMS_POST_REQUEST_SUCCESS_RATIO      ,
        MMS_GET_REQUEST_NUMBER              ,
        MMS_GET_REQUEST_RATIO               ,
        PUSH_REQUEST_NUMBER                 ,
        PUSH_REQUEST_SUCCESS_RATIO          ,
        RADIUS_REQUEST_NUMBER               ,
        RADIUS_REQUEST_SUCCESS_RATIO        ,
        REQUEST_NUMBER                      ,
        REQUEST_SUCCESS_RATIO               ,
        ONLINE_USER_NUMBER                  ,
        GATEWAY_FORWARD_REQUEST_DELAY       ,
        GATEWAY_FORWARD_RESPONSE_DELAY      ,
        SP_DELAY                            ,
        SERVICE_DELAY 
FROM WAP_GATEWAY_SERVICE_ZTE_RAW;
