--------------------------------------------------------
--  DDL for View VWAP_GATEWAY_KPI_ZTE_HOUR
--------------------------------------------------------

  CREATE OR REPLACE VIEW VWAP_GATEWAY_KPI_ZTE_HOUR (FECHA, GATEWAY, GATEWAY_REQUEST_NUMBER, TOTAL_NUMBER, GATEWAY_REQUEST_SUCCESS_NUMBER, GATEWAY_REQUEST_VIRTUAL_NUMBER, GATEWAY_TOP_REQUEST_NUMBER, GATEWAY_SUCCESS_RATE, GATEWAY_VIRTUAL_RATE, GATEWAY_TOP_AVERAGE_CPU_RATE, GATEWAY_AVERAGE_DELAY)
AS
  SELECT FECHA,
    GATEWAY,
    GATEWAY_REQUEST_NUMBER,
    TOTAL_NUMBER,
    GATEWAY_REQUEST_SUCCESS_NUMBER,
    GATEWAY_REQUEST_VIRTUAL_NUMBER,
    GATEWAY_TOP_REQUEST_NUMBER,
    GATEWAY_SUCCESS_RATE,
    GATEWAY_VIRTUAL_RATE,
    GATEWAY_TOP_AVERAGE_CPU_RATE,
    GATEWAY_AVERAGE_DELAY
  FROM WAP_GATEWAY_KPI_ZTE_RAW;
