--------------------------------------------------------
--  DDL for Table WAP_GATEWAY_KPI_ZTE_RAW
--------------------------------------------------------

  CREATE TABLE WAP_GATEWAY_KPI_ZTE_RAW (	
  FECHA DATE, 
	GATEWAY VARCHAR2(50 CHAR), 
	GATEWAY_REQUEST_NUMBER NUMBER, 
	TOTAL_NUMBER NUMBER, 
	GATEWAY_REQUEST_SUCCESS_NUMBER NUMBER, 
	GATEWAY_REQUEST_VIRTUAL_NUMBER NUMBER, 
	GATEWAY_TOP_REQUEST_NUMBER NUMBER, 
	GATEWAY_SUCCESS_RATE NUMBER(6,2), 
	GATEWAY_VIRTUAL_RATE NUMBER(6,2), 
	GATEWAY_TOP_AVERAGE_CPU_RATE NUMBER(6,2), 
	GATEWAY_AVERAGE_DELAY NUMBER(6,2)
   ) 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  DDL for Index WAP_GATEWAY_KPI_ZTE_RAW_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX WAP_GATEWAY_KPI_ZTE_RAW_PK ON WAP_GATEWAY_KPI_ZTE_RAW (FECHA, GATEWAY) 
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table WAP_GATEWAY_KPI_ZTE_RAW
--------------------------------------------------------

  ALTER TABLE WAP_GATEWAY_KPI_ZTE_RAW ADD CONSTRAINT WAP_GATEWAY_KPI_ZTE_RAW_PK PRIMARY KEY (FECHA, GATEWAY)  ENABLE;
  ALTER TABLE WAP_GATEWAY_KPI_ZTE_RAW MODIFY (GATEWAY NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_KPI_ZTE_RAW MODIFY (FECHA NOT NULL ENABLE);
