--------------------------------------------------------
--  DDL for Table WAP_GATEWAY_KPI_ZTE_AUX
--------------------------------------------------------

  CREATE TABLE WAP_GATEWAY_KPI_ZTE_AUX (	
  GATEWAY VARCHAR2(100 CHAR), 
	GATEWAY_REQUEST_NUMBER NUMBER, 
	TOTAL_NUMBER NUMBER, 
	GATEWAY_REQUEST_SUCCESS_NUMBER NUMBER, 
	GATEWAY_REQUEST_VIRTUAL_NUMBER NUMBER, 
	GATEWAY_TOP_REQUEST_NUMBER NUMBER, 
	GATEWAY_SUCCESS_RATE NUMBER(6,2), 
	GATEWAY_VIRTUAL_RATE NUMBER(6,2), 
	GATEWAY_TOP_AVERAGE_CPU_RATE NUMBER(6,2), 
	GATEWAY_AVERAGE_DELAY NUMBER(6,2), 
	NOMBRE_CSV VARCHAR2(500 BYTE)
   ) 
 NOCOMPRESS NOLOGGING
  TABLESPACE TBS_AUXILIAR ;
--------------------------------------------------------
--  Constraints for Table WAP_GATEWAY_KPI_ZTE_AUX
--------------------------------------------------------

  ALTER TABLE WAP_GATEWAY_KPI_ZTE_AUX MODIFY (GATEWAY NOT NULL ENABLE);
