--------------------------------------------------------
--  DDL for Table WAP_GATEWAY_SERVICE_ZTE_RAW
--------------------------------------------------------

  CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_RAW 
   (	FECHA DATE, 
	WAP_BROWSER_REQUEST_NUMBER NUMBER, 
	WAP_BROWSER_REQ_SUCCESS_RATIO NUMBER(6,2), 
	HTTP_BROWSER_REQUEST_NUMBER NUMBER, 
	HTTP_BROWSER_REQ_SUCCESS_RATIO NUMBER(6,2), 
	JAVA_DNLD_REQ_SUCCESS_RATIO NUMBER(6,2), 
	JAVA_DOWNLOAD_REQUEST_NUMBER NUMBER(6,2), 
	MMS_POST_REQUEST_NUMBER NUMBER, 
	MMS_POST_REQUEST_SUCCESS_RATIO NUMBER(6,2), 
	MMS_GET_REQUEST_NUMBER NUMBER, 
	MMS_GET_REQUEST_RATIO NUMBER(6,2), 
	PUSH_REQUEST_NUMBER NUMBER, 
	PUSH_REQUEST_SUCCESS_RATIO NUMBER(6,2), 
	RADIUS_REQUEST_NUMBER NUMBER, 
	RADIUS_REQUEST_SUCCESS_RATIO NUMBER(6,2), 
	REQUEST_NUMBER NUMBER, 
	REQUEST_SUCCESS_RATIO NUMBER(6,2), 
	ONLINE_USER_NUMBER NUMBER, 
	GATEWAY_FORWARD_REQUEST_DELAY NUMBER, 
	GATEWAY_FORWARD_RESPONSE_DELAY NUMBER, 
	SP_DELAY NUMBER, 
	SERVICE_DELAY NUMBER
   ) 
 NOCOMPRESS NOLOGGING
  
  TABLESPACE TBS_HOUR ;

   COMMENT ON COLUMN WAP_GATEWAY_SERVICE_ZTE_RAW.HTTP_BROWSER_REQ_SUCCESS_RATIO IS 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';
   COMMENT ON COLUMN WAP_GATEWAY_SERVICE_ZTE_RAW.JAVA_DNLD_REQ_SUCCESS_RATIO IS 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
--------------------------------------------------------
--  DDL for Index WAP_GATEWAY_SERVICE_ZTE_RA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX WAP_GATEWAY_SERVICE_ZTE_RA_PK ON WAP_GATEWAY_SERVICE_ZTE_RAW (FECHA)  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table WAP_GATEWAY_SERVICE_ZTE_RAW
--------------------------------------------------------

  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW ADD CONSTRAINT WAP_GATEWAY_SERVICE_ZTE_RA_PK PRIMARY KEY (FECHA) ENABLE;
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (SERVICE_DELAY NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (SP_DELAY NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (GATEWAY_FORWARD_RESPONSE_DELAY NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (GATEWAY_FORWARD_REQUEST_DELAY NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (ONLINE_USER_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (REQUEST_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (RADIUS_REQUEST_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (RADIUS_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (PUSH_REQUEST_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (PUSH_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (MMS_GET_REQUEST_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (MMS_GET_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (MMS_POST_REQUEST_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (MMS_POST_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (JAVA_DOWNLOAD_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (JAVA_DNLD_REQ_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (HTTP_BROWSER_REQ_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (HTTP_BROWSER_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (WAP_BROWSER_REQ_SUCCESS_RATIO NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (WAP_BROWSER_REQUEST_NUMBER NOT NULL ENABLE);
  ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_RAW MODIFY (FECHA NOT NULL ENABLE);
