--------------------------------------------------------
--  DDL for Table MOBILEUM_ASP_AUX
--------------------------------------------------------

  CREATE TABLE MOBILEUM_ASP_AUX 
   (	PAIS CHAR(3 CHAR) GENERATED ALWAYS AS (SUBSTR(ARCHIVO,-16,3)) VIRTUAL , 
	FECHA VARCHAR2(20 BYTE), 
	CNT_LLAMADAS NUMBER, 
	CNT_POLITICA_RESTRICCION NUMBER, 
	CNT_BOLQ_REL_TIPO_GEST NUMBER, 
	CNT_BLOQ_RAN_REL NUMBER, 
	CNT_PERMITIERON_CONTINUAR NUMBER, 
	CNT_CONECTADAS_VOICE_MAIL NUMBER, 
	CNT_CONECTADA_ANUNCIO_SWITCH NUMBER, 
	ARCHIVO VARCHAR2(500 BYTE)
   )
 NOCOMPRESS NOLOGGING
  
  TABLESPACE TBS_AUXILIAR ;
