--------------------------------------------------------
--  DDL for Table MOBILEUM_ASP_HOUR
--------------------------------------------------------

  CREATE TABLE MOBILEUM_ASP_HOUR 
   (	PAIS CHAR(3 CHAR), 
	FECHA DATE, 
	CNT_LLAMADAS NUMBER, 
	CNT_POLITICA_RESTRICCION NUMBER, 
	CNT_BOLQ_REL_TIPO_GEST NUMBER, 
	CNT_BLOQ_RAN_REL NUMBER, 
	CNT_PERMITIERON_CONTINUAR NUMBER, 
	CNT_CONECTADAS_VOICE_MAIL NUMBER, 
	CNT_CONECTADA_ANUNCIO_SWITCH NUMBER
   ) 
 NOCOMPRESS NOLOGGING
  
  TABLESPACE TBS_HOUR ;

   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.PAIS IS 'Pais. Ej. ARG';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.FECHA IS 'Rango horario.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_LLAMADAS IS 'Cantidad de llamadas totales.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_POLITICA_RESTRICCION IS 'Cantidad de llamadas que matchearon alguna política de restricción.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_BOLQ_REL_TIPO_GEST IS 'Cantidad de llamadas bloqueadas con release tipo congestión.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_BLOQ_RAN_REL IS 'Cantidad de llamadas bloqueadas con random releases.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_PERMITIERON_CONTINUAR IS 'Cantidad de llamadas que se permitieron continuar.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_CONECTADAS_VOICE_MAIL IS 'Cantidad de llamadas conectadas al Voice Mail.';
   COMMENT ON COLUMN MOBILEUM_ASP_HOUR.CNT_CONECTADA_ANUNCIO_SWITCH IS 'Cantidad de llamadas conectadas a un anuncio en el switch.';
   COMMENT ON TABLE MOBILEUM_ASP_HOUR  IS 'Tabla contenedora de datos correspondientes a plataforma MOBILEUM, proveedor ANTISPAMMING (ASP)';
--------------------------------------------------------
--  DDL for Index MOBILEUM_ASP_HOUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX MOBILEUM_ASP_HOUR_PK ON MOBILEUM_ASP_HOUR (PAIS, FECHA)
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table MOBILEUM_ASP_HOUR
--------------------------------------------------------

  ALTER TABLE MOBILEUM_ASP_HOUR ADD CONSTRAINT MOBILEUM_ASP_HOUR_PK PRIMARY KEY (PAIS, FECHA)  ENABLE;
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_CONECTADA_ANUNCIO_SWITCH NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_CONECTADAS_VOICE_MAIL NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_PERMITIERON_CONTINUAR NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_BLOQ_RAN_REL NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_BOLQ_REL_TIPO_GEST NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_POLITICA_RESTRICCION NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (CNT_LLAMADAS NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (FECHA NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_HOUR MODIFY (PAIS NOT NULL ENABLE);
