--------------------------------------------------------
--  DDL for Table MOBILEUM_ASP_DAY
--------------------------------------------------------

  CREATE TABLE MOBILEUM_ASP_DAY 
   (	PAIS CHAR(3 CHAR), 
	FECHA DATE, 
	CNT_LLAMADAS NUMBER, 
	CNT_POLITICA_RESTRICCION NUMBER, 
	CNT_BOLQ_REL_TIPO_GEST NUMBER, 
	CNT_BLOQ_RAN_REL NUMBER, 
	CNT_PERMITIERON_CONTINUAR NUMBER, 
	CNT_CONECTADAS_VOICE_MAIL NUMBER, 
	CNT_CONECTADA_ANUNCIO_SWITCH NUMBER
   ) 
 NOCOMPRESS NOLOGGING
  
  TABLESPACE TBS_DAY ;

   COMMENT ON TABLE MOBILEUM_ASP_DAY  IS 'Sumarizaciones del MOBILEUM_ASP a nivel DAY';
--------------------------------------------------------
--  Constraints for Table MOBILEUM_ASP_DAY
--------------------------------------------------------

  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_CONECTADA_ANUNCIO_SWITCH NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_CONECTADAS_VOICE_MAIL NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_PERMITIERON_CONTINUAR NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_BLOQ_RAN_REL NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_BOLQ_REL_TIPO_GEST NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_POLITICA_RESTRICCION NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (CNT_LLAMADAS NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (FECHA NOT NULL ENABLE);
  ALTER TABLE MOBILEUM_ASP_DAY MODIFY (PAIS NOT NULL ENABLE);
