--------------------------------------------------------
--  DDL for Table TEC_CE_CDC_TPS_RAW
--------------------------------------------------------

  CREATE TABLE TEC_CE_CDC_TPS_RAW 
   (	START_DTIME DATE, 
	END_DTIME DATE, 
	PAIS CHAR(3 CHAR), 
	MAX_TPS NUMBER, 
	MAX_CAP_HW NUMBER DEFAULT 1, 
	MAX_CAP_SW NUMBER DEFAULT 1
   ) NOCOMPRESS NOLOGGING
   PARTITION BY RANGE (START_DTIME)
   (
    PARTITION CECDCTPSRAW201510 VALUES LESS THAN (TO_DATE('01.11.2015','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201511 VALUES LESS THAN (TO_DATE('01.12.2015','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201512 VALUES LESS THAN (TO_DATE('01.01.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201601 VALUES LESS THAN (TO_DATE('01.02.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201602 VALUES LESS THAN (TO_DATE('01.03.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201603 VALUES LESS THAN (TO_DATE('01.04.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201604 VALUES LESS THAN (TO_DATE('01.05.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201605 VALUES LESS THAN (TO_DATE('01.06.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201606 VALUES LESS THAN (TO_DATE('01.07.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201607 VALUES LESS THAN (TO_DATE('01.08.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201608 VALUES LESS THAN (TO_DATE('01.09.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201609 VALUES LESS THAN (TO_DATE('01.10.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201610 VALUES LESS THAN (TO_DATE('01.11.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201611 VALUES LESS THAN (TO_DATE('01.12.2016','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80,
    PARTITION CECDCTPSRAW201612 VALUES LESS THAN (TO_DATE('01.01.2017','DD.MM.YYYY')) TABLESPACE TBS_HOUR PCTFREE 10 PCTUSED 80
   )
  TABLESPACE TBS_HOUR ;
--------------------------------------------------------
--  Constraints for Table TEC_CE_CDC_TPS_RAW
--------------------------------------------------------

  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (MAX_CAP_SW NOT NULL ENABLE);
  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (MAX_CAP_HW NOT NULL ENABLE);
  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (MAX_TPS NOT NULL ENABLE);
  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (PAIS NOT NULL ENABLE);
  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (END_DTIME NOT NULL ENABLE);
  ALTER TABLE TEC_CE_CDC_TPS_RAW MODIFY (START_DTIME NOT NULL ENABLE);
