CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_RAW(
TIME_                               DATE NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE
);

comment on column WAP_GATEWAY_SERVICE_ZTE_RAW.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_RAW.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';

