CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_RAW(
TIME_                               DATE NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
JAVA_DOWNLOAD_REQUEST_NUMBER        NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE
);

comment on column WAP_GATEWAY_SERVICE_ZTE_RAW.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_RAW.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';


-- DROP TABLE WAP_GATEWAY_SERVICE_ZTE_AUX;

CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_AUX(
HORA                                VARCHAR2(5 CHAR) NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
JAVA_DOWNLOAD_REQUEST_NUMBER        NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE,
NOMBRE_CSV                          VARCHAR2(500 CHAR),
TIME_                               DATE GENERATED ALWAYS AS (to_date(SUBSTR(SUBSTR(nombre_csv,INSTR(nombre_csv,'_',-1)+1,8),7,2)||
                                                                    '.'||
                                                                    SUBSTR(SUBSTR(nombre_csv,INSTR(nombre_csv,'_',-1)+1,8),5,2)||
                                                                    '.'||
                                                                    SUBSTR(SUBSTR(nombre_csv,INSTR(nombre_csv,'_',-1)+1,8),1,4)||' '||HORA,'dd.mm.yyyy HH24:MI')) VIRTUAL
);

comment on column WAP_GATEWAY_SERVICE_ZTE_AUX.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_AUX.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';
--
-- 
CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_DAY(
FECHA                               DATE NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
JAVA_DOWNLOAD_REQUEST_NUMBER        NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE
);

ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_DAY ADD CONSTRAINT WAP_GATEWAY_SERVICE_ZTE_DAY_PK PRIMARY KEY (FECHA);

comment on column WAP_GATEWAY_SERVICE_ZTE_DAY.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_DAY.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';
--
--
CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_BH(
FECHA                               DATE NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
JAVA_DOWNLOAD_REQUEST_NUMBER        NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE
);

--ALTER TABLE WAP_GATEWAY_SERVICE_ZTE_BH ADD CONSTRAINT WAP_GATEWAY_SERVICE_ZTE_DAY_PK PRIMARY KEY (FECHA);

comment on column WAP_GATEWAY_SERVICE_ZTE_BH.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_BH.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';

--
CREATE TABLE WAP_GATEWAY_SERVICE_ZTE_IBHW(
FECHA                               DATE NOT NULL ENABLE,
WAP_BROWSER_REQUEST_NUMBER          NUMBER NOT NULL ENABLE,
WAP_BROWSER_REQ_SUCCESS_RATIO       NUMBER(6,2) NOT NULL ENABLE,
HTTP_BROWSER_REQUEST_NUMBER         NUMBER NOT NULL ENABLE,
HTTP_BROWSER_REQ_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
JAVA_DNLD_REQ_SUCCESS_RATIO         NUMBER(6,2) NOT NULL ENABLE,
JAVA_DOWNLOAD_REQUEST_NUMBER        NUMBER(6,2) NOT NULL ENABLE,
MMS_POST_REQUEST_NUMBER             NUMBER NOT NULL ENABLE,
MMS_POST_REQUEST_SUCCESS_RATIO      NUMBER(6,2) NOT NULL ENABLE,
MMS_GET_REQUEST_NUMBER              NUMBER NOT NULL ENABLE,
MMS_GET_REQUEST_RATIO               NUMBER(6,2) NOT NULL ENABLE,
PUSH_REQUEST_NUMBER                 NUMBER NOT NULL ENABLE,
PUSH_REQUEST_SUCCESS_RATIO          NUMBER(6,2) NOT NULL ENABLE,
RADIUS_REQUEST_NUMBER               NUMBER NOT NULL ENABLE,
RADIUS_REQUEST_SUCCESS_RATIO        NUMBER(6,2) NOT NULL ENABLE,
REQUEST_NUMBER                      NUMBER NOT NULL ENABLE,
REQUEST_SUCCESS_RATIO               NUMBER(6,2) NOT NULL ENABLE,
ONLINE_USER_NUMBER                  NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_REQUEST_DELAY       NUMBER NOT NULL ENABLE,
GATEWAY_FORWARD_RESPONSE_DELAY      NUMBER NOT NULL ENABLE,
SP_DELAY                            NUMBER NOT NULL ENABLE,
SERVICE_DELAY                       NUMBER NOT NULL ENABLE
);


comment on column WAP_GATEWAY_SERVICE_ZTE_IBHW.JAVA_DNLD_REQ_SUCCESS_RATIO  is 'Abreviatura de la colunma original JAVA_DOWNLOAD_REQUEST_SUCCESS_RATIO';
comment on column WAP_GATEWAY_SERVICE_ZTE_IBHW.HTTP_BROWSER_REQ_SUCCESS_RATIO is 'Abreviatura de la colunma original HTTP_BROWSER_REQUEST_SUCCESS_RATIO';