CREATE TABLE WAP_GATEWAY_KPI_ZTE(
FECHA                           DATE NOT NULL ENABLE,
GATEWAY                         VARCHAR2(50 CHAR) NOT NULL ENABLE,
GATEWAY_REQUEST_NUMBER          NUMBER,
TOTAL_NUMBER                    NUMBER,
GATEWAY_REQUEST_SUCCESS_NUMBER  NUMBER,
GATEWAY_REQUEST_VIRTUAL_NUMBER  NUMBER,
GATEWAY_TOP_REQUEST_NUMBER      NUMBER,
GATEWAY_SUCCESS_RATE            NUMBER(6,2),
GATEWAY_VIRTUAL_RATE            NUMBER(6,2),
GATEWAY_TOP_AVERAGE_CPU_RATE    NUMBER(6,2),
GATEWAY_AVERAGE_DELAY           NUMBER(6,2)
);
