CREATE TABLE WAP_GATEWAY_KPI_ZTE_RAW(
FECHA                           DATE NOT NULL ENABLE,
GATEWAY                         VARCHAR2(50 CHAR) NOT NULL ENABLE,
GATEWAY_REQUEST_NUMBER          NUMBER,
TOTAL_NUMBER                    NUMBER,
GATEWAY_REQUEST_SUCCESS_NUMBER  NUMBER,
GATEWAY_REQUEST_VIRTUAL_NUMBER  NUMBER,
GATEWAY_TOP_REQUEST_NUMBER      NUMBER,
GATEWAY_SUCCESS_RATE            NUMBER(6,2),
GATEWAY_VIRTUAL_RATE            NUMBER(6,2),
GATEWAY_TOP_AVERAGE_CPU_RATE    NUMBER(6,2),
GATEWAY_AVERAGE_DELAY           NUMBER(6,2)
);

ALTER TABLE WAP_GATEWAY_KPI_ZTE_RAW ADD CONSTRAINT WAP_GATEWAY_KPI_ZTE_RAW_PK PRIMARY KEY (FECHA,GATEWAY);

CREATE OR REPLACE VIEW VWAP_GATEWAY_KPI_ZTE_DAY AS
SELECT  FECHA                           ,
        GATEWAY                         ,
        GATEWAY_REQUEST_NUMBER          ,
        TOTAL_NUMBER                    ,
        GATEWAY_REQUEST_SUCCESS_NUMBER  ,
        GATEWAY_REQUEST_VIRTUAL_NUMBER  ,
        GATEWAY_TOP_REQUEST_NUMBER      ,
        GATEWAY_SUCCESS_RATE            ,
        GATEWAY_VIRTUAL_RATE            ,
        GATEWAY_TOP_AVERAGE_CPU_RATE    ,
        GATEWAY_AVERAGE_DELAY
FROM WAP_GATEWAY_KPI_ZTE_RAW;
